import hashlib
import logging
from dataclasses import dataclass
from typing import Any

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ChunkingConfig:
    """
    Configuration for splitting extracted PDF text into smaller chunks.
    """

    chunk_size: int = 1000
    chunk_overlap: int = 150


class ChunkingException(Exception):
    """Raised when document chunking fails."""


class DocumentChunker:
    """
    Responsible for converting page-level Documents into smaller chunk-level Documents.

    This class does NOT:
    - load PDFs
    - create embeddings
    - store documents in Chroma
    - call the LLM
    """

    def __init__(self, config: ChunkingConfig | None = None):
        self.config = config or ChunkingConfig()

        self._splitter = RecursiveCharacterTextSplitter(
            chunk_size=self.config.chunk_size,
            chunk_overlap=self.config.chunk_overlap,
            separators=["\n\n", "\n", ". ", " ", ""],
        )

    def chunk_documents(self, documents: list[Document]) -> list[Document]:
        """
        Split many page-level Documents into chunk-level Documents.
        """

        if not documents:
            raise ChunkingException("Cannot chunk an empty document list.")

        try:
            logger.info(
                "Chunking %s documents with chunk_size=%s and chunk_overlap=%s.",
                len(documents),
                self.config.chunk_size,
                self.config.chunk_overlap,
            )

            chunked_documents: list[Document] = []

            for document in documents:
                chunks = self._split_document(document)
                chunked_documents.extend(chunks)

            logger.info("Created %s total chunks.", len(chunked_documents))

            return chunked_documents

        except ChunkingException:
            raise
        except Exception as exc:
            raise ChunkingException("Failed to chunk documents.") from exc

    def _split_document(self, document: Document) -> list[Document]:
        """
        Split one page-level Document into multiple chunk-level Documents.
        """

        if not document.page_content or not document.page_content.strip():
            return []

        split_texts = self._splitter.split_text(document.page_content)

        chunks: list[Document] = []

        for chunk_index, text in enumerate(split_texts):
            cleaned_text = text.strip()

            if not cleaned_text:
                continue

            metadata = dict(document.metadata)
            metadata["chunk_index"] = chunk_index
            metadata["chunk_id"] = self._build_chunk_id(
                content=cleaned_text,
                metadata=metadata,
            )

            chunks.append(
                Document(
                    page_content=cleaned_text,
                    metadata=metadata,
                )
            )

        return chunks

    def build_ids(self, documents: list[Document]) -> list[str]:
        """
        Build stable IDs for Chroma from chunk metadata.

        Chroma can use these IDs to avoid random autogenerated IDs.
        """

        ids: list[str] = []

        for document in documents:
            chunk_id = document.metadata.get("chunk_id")

            if not chunk_id:
                raise ChunkingException(
                    "Cannot build Chroma IDs because a document is missing chunk_id."
                )

            ids.append(str(chunk_id))

        return ids

    def _build_chunk_id(self, content: str, metadata: dict[str, Any]) -> str:
        """
        Build a stable chunk ID from source, page, chunk index, and content hash.
        """

        source = metadata.get("source", "unknown-source")
        page = metadata.get("page", "unknown-page")
        chunk_index = metadata.get("chunk_index", "unknown-chunk")

        content_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()[:12]

        return f"{source}:page-{page}:chunk-{chunk_index}:{content_hash}"